# Generated by Django 2.0 on 2020-04-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_create_time', models.DateTimeField()),
                ('teacher_email', models.EmailField(max_length=254)),
                ('student_id', models.IntegerField()),
                ('homework_content', models.CharField(max_length=50)),
                ('homework_deadline', models.CharField(max_length=20)),
                ('handIn_homework', models.FileField(null=True, upload_to='avatar/')),
                ('handIn_time', models.DateTimeField(null=True)),
                ('isLate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_create_time', models.DateTimeField()),
                ('teacher_email', models.EmailField(max_length=254)),
                ('student_id', models.IntegerField()),
                ('notice_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('sgrade', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('isTeacher', models.CharField(max_length=50)),
            ],
        ),
    ]
