# Generated by Django 2.0 on 2020-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_create_time', models.DateTimeField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('homework_id', models.IntegerField()),
                ('homework_content', models.CharField(max_length=50)),
                ('homework_deadline', models.DateTimeField(max_length=20)),
                ('handIn_homework', models.FileField(null=True, upload_to='avatar')),
                ('handIn_time', models.DateTimeField(null=True)),
                ('isLate', models.BooleanField(default=False)),
                ('isComplete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Homework1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('homework_id', models.IntegerField()),
                ('iscorrect', models.NullBooleanField()),
                ('tcomment', models.CharField(default='待评论！', max_length=200)),
                ('iscommented', models.BooleanField(default=False)),
                ('isComplete', models.BooleanField(default=False)),
                ('feedback_homework', models.FileField(null=True, upload_to='media')),
                ('feedback_comment', models.CharField(default='待评论！', max_length=200)),
                ('isright', models.BooleanField(default=False)),
                ('isfeedback', models.BooleanField(default=False)),
                ('homework_content', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_create_time', models.DateTimeField()),
                ('teacher_email', models.EmailField(max_length=254)),
                ('student_id', models.IntegerField()),
                ('notice_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='objective_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('homework_create_time', models.DateTimeField()),
                ('homework_deadline', models.DateTimeField(max_length=20)),
                ('item_content', models.CharField(max_length=200)),
                ('mean', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='objective_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('item_content', models.CharField(max_length=200)),
                ('item_num', models.IntegerField()),
                ('answer', models.CharField(max_length=200)),
                ('student_answer', models.CharField(max_length=200, null=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('homework_create_time', models.DateTimeField()),
                ('homework_deadline', models.DateTimeField(max_length=20)),
                ('item_id', models.IntegerField(null=True)),
                ('handIn_time', models.DateTimeField(null=True)),
                ('isLate', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('sgrade', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sage', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('homework_content', models.CharField(default='1', max_length=50)),
                ('homework_deadline', models.DateTimeField(max_length=20)),
                ('homework_create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('isTeacher', models.CharField(max_length=50)),
            ],
        ),
    ]
