# Generated by Django 2.0 on 2020-04-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_deadline',
            field=models.DateTimeField(max_length=20),
        ),
    ]
